/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthedAdminRouteImport } from './routes/_authed/admin'
import { Route as AuthedBillingRouteImport } from './routes/_authed/billing'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedQueueRouteImport } from './routes/_authed/queue'
import { Route as AuthedAdminMembersRouteImport } from './routes/_authed/admin/members'
import { Route as AuthedAdminStringsRouteImport } from './routes/_authed/admin/strings'
import { Route as AuthedBillingIndexRouteImport } from './routes/_authed/billing/index'
import { Route as AuthedBillingPayoutsRouteImport } from './routes/_authed/billing/payouts'
import { Route as AuthedQueueIndexRouteImport } from './routes/_authed/queue/index'
import { Route as AuthedQueueIdRouteImport } from './routes/_authed/queue/$id'
import { Route as AuthedRacketsIndexRouteImport } from './routes/_authed/rackets/index'
import { Route as AuthedRacketsIdRouteImport } from './routes/_authed/rackets/$id'
import { Route as AuthedRacketsNewRouteImport } from './routes/_authed/rackets/new'
import { Route as AuthedRequestsIndexRouteImport } from './routes/_authed/requests/index'
import { Route as AuthedRequestsIdRouteImport } from './routes/_authed/requests/$id'
import { Route as AuthedRequestsNewRouteImport } from './routes/_authed/requests/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedAdminRoute = AuthedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBillingRoute = AuthedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQueueRoute = AuthedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAdminMembersRoute = AuthedAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedAdminStringsRoute = AuthedAdminStringsRouteImport.update({
  id: '/strings',
  path: '/strings',
  getParentRoute: () => AuthedAdminRoute,
} as any)
const AuthedBillingIndexRoute = AuthedBillingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedBillingRoute,
} as any)
const AuthedBillingPayoutsRoute = AuthedBillingPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AuthedBillingRoute,
} as any)
const AuthedQueueIndexRoute = AuthedQueueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedQueueRoute,
} as any)
const AuthedQueueIdRoute = AuthedQueueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedQueueRoute,
} as any)
const AuthedRacketsIndexRoute = AuthedRacketsIndexRouteImport.update({
  id: '/rackets/',
  path: '/rackets/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRacketsIdRoute = AuthedRacketsIdRouteImport.update({
  id: '/rackets/$id',
  path: '/rackets/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRacketsNewRoute = AuthedRacketsNewRouteImport.update({
  id: '/rackets/new',
  path: '/rackets/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsIndexRoute = AuthedRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsIdRoute = AuthedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsNewRoute = AuthedRequestsNewRouteImport.update({
  id: '/requests/new',
  path: '/requests/new',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/billing': typeof AuthedBillingRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/queue': typeof AuthedQueueRouteWithChildren
  '/admin/members': typeof AuthedAdminMembersRoute
  '/admin/strings': typeof AuthedAdminStringsRoute
  '/billing/payouts': typeof AuthedBillingPayoutsRoute
  '/queue/$id': typeof AuthedQueueIdRoute
  '/rackets/$id': typeof AuthedRacketsIdRoute
  '/rackets/new': typeof AuthedRacketsNewRoute
  '/requests/$id': typeof AuthedRequestsIdRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/billing/': typeof AuthedBillingIndexRoute
  '/queue/': typeof AuthedQueueIndexRoute
  '/rackets/': typeof AuthedRacketsIndexRoute
  '/requests/': typeof AuthedRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AuthedAdminRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/admin/members': typeof AuthedAdminMembersRoute
  '/admin/strings': typeof AuthedAdminStringsRoute
  '/billing/payouts': typeof AuthedBillingPayoutsRoute
  '/queue/$id': typeof AuthedQueueIdRoute
  '/rackets/$id': typeof AuthedRacketsIdRoute
  '/rackets/new': typeof AuthedRacketsNewRoute
  '/requests/$id': typeof AuthedRequestsIdRoute
  '/requests/new': typeof AuthedRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/billing': typeof AuthedBillingIndexRoute
  '/queue': typeof AuthedQueueIndexRoute
  '/rackets': typeof AuthedRacketsIndexRoute
  '/requests': typeof AuthedRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/pending': typeof PendingRoute
  '/signup': typeof SignupRoute
  '/_authed/admin': typeof AuthedAdminRouteWithChildren
  '/_authed/billing': typeof AuthedBillingRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/queue': typeof AuthedQueueRouteWithChildren
  '/_authed/admin/members': typeof AuthedAdminMembersRoute
  '/_authed/admin/strings': typeof AuthedAdminStringsRoute
  '/_authed/billing/payouts': typeof AuthedBillingPayoutsRoute
  '/_authed/queue/$id': typeof AuthedQueueIdRoute
  '/_authed/rackets/$id': typeof AuthedRacketsIdRoute
  '/_authed/rackets/new': typeof AuthedRacketsNewRoute
  '/_authed/requests/$id': typeof AuthedRequestsIdRoute
  '/_authed/requests/new': typeof AuthedRequestsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authed/billing/': typeof AuthedBillingIndexRoute
  '/_authed/queue/': typeof AuthedQueueIndexRoute
  '/_authed/rackets/': typeof AuthedRacketsIndexRoute
  '/_authed/requests/': typeof AuthedRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/queue'
    | '/admin/members'
    | '/admin/strings'
    | '/billing/payouts'
    | '/queue/$id'
    | '/rackets/$id'
    | '/rackets/new'
    | '/requests/$id'
    | '/requests/new'
    | '/api/auth/$'
    | '/billing/'
    | '/queue/'
    | '/rackets/'
    | '/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/pending'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/admin/members'
    | '/admin/strings'
    | '/billing/payouts'
    | '/queue/$id'
    | '/rackets/$id'
    | '/rackets/new'
    | '/requests/$id'
    | '/requests/new'
    | '/api/auth/$'
    | '/billing'
    | '/queue'
    | '/rackets'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/pending'
    | '/signup'
    | '/_authed/admin'
    | '/_authed/billing'
    | '/_authed/dashboard'
    | '/_authed/queue'
    | '/_authed/admin/members'
    | '/_authed/admin/strings'
    | '/_authed/billing/payouts'
    | '/_authed/queue/$id'
    | '/_authed/rackets/$id'
    | '/_authed/rackets/new'
    | '/_authed/requests/$id'
    | '/_authed/requests/new'
    | '/api/auth/$'
    | '/_authed/billing/'
    | '/_authed/queue/'
    | '/_authed/rackets/'
    | '/_authed/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  PendingRoute: typeof PendingRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/admin': {
      id: '/_authed/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthedAdminRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/billing': {
      id: '/_authed/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthedBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/queue': {
      id: '/_authed/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthedQueueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/admin/members': {
      id: '/_authed/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthedAdminMembersRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/admin/strings': {
      id: '/_authed/admin/strings'
      path: '/strings'
      fullPath: '/admin/strings'
      preLoaderRoute: typeof AuthedAdminStringsRouteImport
      parentRoute: typeof AuthedAdminRoute
    }
    '/_authed/billing/': {
      id: '/_authed/billing/'
      path: '/'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthedBillingIndexRouteImport
      parentRoute: typeof AuthedBillingRoute
    }
    '/_authed/billing/payouts': {
      id: '/_authed/billing/payouts'
      path: '/payouts'
      fullPath: '/billing/payouts'
      preLoaderRoute: typeof AuthedBillingPayoutsRouteImport
      parentRoute: typeof AuthedBillingRoute
    }
    '/_authed/queue/': {
      id: '/_authed/queue/'
      path: '/'
      fullPath: '/queue/'
      preLoaderRoute: typeof AuthedQueueIndexRouteImport
      parentRoute: typeof AuthedQueueRoute
    }
    '/_authed/queue/$id': {
      id: '/_authed/queue/$id'
      path: '/$id'
      fullPath: '/queue/$id'
      preLoaderRoute: typeof AuthedQueueIdRouteImport
      parentRoute: typeof AuthedQueueRoute
    }
    '/_authed/rackets/': {
      id: '/_authed/rackets/'
      path: '/rackets'
      fullPath: '/rackets/'
      preLoaderRoute: typeof AuthedRacketsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rackets/$id': {
      id: '/_authed/rackets/$id'
      path: '/rackets/$id'
      fullPath: '/rackets/$id'
      preLoaderRoute: typeof AuthedRacketsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/rackets/new': {
      id: '/_authed/rackets/new'
      path: '/rackets/new'
      fullPath: '/rackets/new'
      preLoaderRoute: typeof AuthedRacketsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests/': {
      id: '/_authed/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthedRequestsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests/$id': {
      id: '/_authed/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthedRequestsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests/new': {
      id: '/_authed/requests/new'
      path: '/requests/new'
      fullPath: '/requests/new'
      preLoaderRoute: typeof AuthedRequestsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthedAdminRouteChildren {
  AuthedAdminMembersRoute: typeof AuthedAdminMembersRoute
  AuthedAdminStringsRoute: typeof AuthedAdminStringsRoute
}

const AuthedAdminRouteChildren: AuthedAdminRouteChildren = {
  AuthedAdminMembersRoute: AuthedAdminMembersRoute,
  AuthedAdminStringsRoute: AuthedAdminStringsRoute,
}

const AuthedAdminRouteWithChildren = AuthedAdminRoute._addFileChildren(
  AuthedAdminRouteChildren,
)

interface AuthedBillingRouteChildren {
  AuthedBillingPayoutsRoute: typeof AuthedBillingPayoutsRoute
  AuthedBillingIndexRoute: typeof AuthedBillingIndexRoute
}

const AuthedBillingRouteChildren: AuthedBillingRouteChildren = {
  AuthedBillingPayoutsRoute: AuthedBillingPayoutsRoute,
  AuthedBillingIndexRoute: AuthedBillingIndexRoute,
}

const AuthedBillingRouteWithChildren = AuthedBillingRoute._addFileChildren(
  AuthedBillingRouteChildren,
)

interface AuthedQueueRouteChildren {
  AuthedQueueIdRoute: typeof AuthedQueueIdRoute
  AuthedQueueIndexRoute: typeof AuthedQueueIndexRoute
}

const AuthedQueueRouteChildren: AuthedQueueRouteChildren = {
  AuthedQueueIdRoute: AuthedQueueIdRoute,
  AuthedQueueIndexRoute: AuthedQueueIndexRoute,
}

const AuthedQueueRouteWithChildren = AuthedQueueRoute._addFileChildren(
  AuthedQueueRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAdminRoute: typeof AuthedAdminRouteWithChildren
  AuthedBillingRoute: typeof AuthedBillingRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedQueueRoute: typeof AuthedQueueRouteWithChildren
  AuthedRacketsIdRoute: typeof AuthedRacketsIdRoute
  AuthedRacketsNewRoute: typeof AuthedRacketsNewRoute
  AuthedRequestsIdRoute: typeof AuthedRequestsIdRoute
  AuthedRequestsNewRoute: typeof AuthedRequestsNewRoute
  AuthedRacketsIndexRoute: typeof AuthedRacketsIndexRoute
  AuthedRequestsIndexRoute: typeof AuthedRequestsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAdminRoute: AuthedAdminRouteWithChildren,
  AuthedBillingRoute: AuthedBillingRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedQueueRoute: AuthedQueueRouteWithChildren,
  AuthedRacketsIdRoute: AuthedRacketsIdRoute,
  AuthedRacketsNewRoute: AuthedRacketsNewRoute,
  AuthedRequestsIdRoute: AuthedRequestsIdRoute,
  AuthedRequestsNewRoute: AuthedRequestsNewRoute,
  AuthedRacketsIndexRoute: AuthedRacketsIndexRoute,
  AuthedRequestsIndexRoute: AuthedRequestsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  PendingRoute: PendingRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
